### ISSUE TITLE
Pip install option

### ISSUE THREAD

**Issue by znicholls** [svenevs/elba#2]
Hi @svenevs, thanks for your efforts here and also in the many discussions on https://github.com/sphinx-doc/sphinx/issues/7077. I think elba is just what I was looking for! Is there a way to install it via pip? If no, would you be interested in releasing it on pypi? Thanks!

**Comment by svenevs** [comment]
Hey! Sorry for the delay, yeah I haven't looked at this in a long while but happy to deploy it. Would you be interested in comaintaining this (here and on PyPI)?

I'll check out the issue you posted this weekend, probably whatever broke will determine our minimum supported sphinx version. Given the nature of this package, unless the monkey patch breaks I don't anticipate a lot of traffic here.

**Comment by znicholls** [comment]
Hi @svenevs, just wondering if you had a chance to look at #3 or #4 again?

**Comment by svenevs** [comment]
@znicholls Sorry, I got lost last time I picked it up. I have a calendar reminder set for this weekend, feel free to re-nudge me on Saturday as friendly reminder.

I was looking at renaming options and was thinking of just renaming this repo `sphinx-ext-napoleon-elba` and adding `sphinx_ext_napoleon_elba`, I found https://github.com/tox-dev/sphinx-autodoc-typehints (it seems like there were some forks and then eventually `tox` picked it up).  They've got a closed issue about `napoleon` support linking to forks that don't seem to exist anymore, or are outdated.  Did you already look at these during your quest?  I feel like `sphinx-autodoc-typehints` may already be solving the problem?  It is worth investigation, but if it does not I will just rename this and package it.  If it becomes high maintenance though, I am not in a position to do that.

**Comment by svenevs** [comment]
https://github.com/tox-dev/sphinx-autodoc-typehints/issues/15

sorry linking the issue

**Comment by svenevs** [comment]
woah yeah https://github.com/tox-dev/sphinx-autodoc-typehints/pull/311 nice i think they've got a better / more robust solution. i will definitely test this weekend, only catch i've seen is you may need to ensure that their extension is added after autodoc and napoleon (sphinx processes extensions in that list by order). 

depending on analysis this repo will either get archived and update the sphinx issue that leads here, or renamed and deployed i just need a few hours to get the CI/CD setup and get it running locally

**Comment by znicholls** [comment]
Nice find! Funny, I opened this Jan 12 then that fix came through Jan 21, must have been something happening in the cosmos. Thanks for all your work, I hope the fix in autodoc supports having something like this

```python
Returns
--------
Description without indent
```

rather than forcing the indent like this

```python
Returns
--------
    Description with indent
```

Either way, good enough.

Thanks again for all your efforts with elba and support on this issue!

**Comment by znicholls** [comment]
> rather than forcing the indent like this

Looks like this is forced, not the end of the world (but not as nice as elba)
